# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42b4b61be100550531a0505290f0ffda0ef58d1795ce4a2b004b72bac5c4b942d32212acdd2fefcc8c1839cc5e948f80118d5bcf287cc89df52f16626e40e6a9

test:
  secret_key_base: 418fd081aea85aa62c8896a4b2cb8e5f47fcc2435b77f191d5f0f83fa28683ada24d9d9d01717bef4bdd335fea14f6b9dded1cb1ea1db4e90f9fd11b0143fe71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
